Common:
    experiment_name : TestRun
    mode : train  # Possible values: train, eval
    env_id : Goalkeeper-v0  # Possible values: Goalkeeper-v0, Foosball-v0
    algorithm : ppo  # Possible values: a2c, ddpg, dqn, ppo, sac, td3, ars, qrdqn, tqc, trpo, ppo_lstm

Wrapper:
    EnvWrapper:
        use_add_actions_to_observation_wrapper: False  # If false, the observations won't contain the taken actions
        use_goal_env_wrapper : False  # Turn this on if you want to use Hindsight Experience Replay (HerReplayBuffer), you must still specify HER in the algorithm's hyperparameters
        use_action_space_wrapper: False
        ActionSpaceWrapper :
            action_space : multi_discrete  # Possible values: continuous, discrete, multi_discrete
            lateral_bins : 5
            angular_bins : 5
    VecEnvWrapper:
        use_vec_pbrs_wrapper: False
        use_vec_normalize_wrapper: True
        VecNormalizeWrapper:
            norm_obs: True
            norm_reward: True
            clip_obs: 10
            clip_reward: 10
        use_video_recording_wrapper: True  # Works only if the environment render_mode == 'rgb_array', doesn't support human rendering and recording
        VecVideoRecorderWrapper:
            video_length: 1000
            video_interval: !!float 2e5
            video_log_path_suffix: videos

Training:
    seeds : [100, 200, 300]
    n_envs : 1
    total_timesteps : !!float 1.5e6
    tb_log_name : training_run
    vec_normalize_load_path : null

Evaluation:
    eval_seed : 1
    n_eval_envs : 1
    model_path : experiments/TestRun/training/seed-100/eval/best/best_model.zip
    vec_normalize_load_path : experiments/TestRun/training/seed-100/eval/best/vecnormalize.pkl
    n_eval_episodes : 100

Callbacks:
    use_tensorboard_callback: True
    use_eval_callback: False
    EvalCallback:
        eval_n_envs: 1
        eval_seed: 10
        eval_n_episodes: 25
        eval_freq: !!float 1e5
        eval_deterministic: True
    use_checkpoint_callback: False
    CheckpointCallback:
        checkpoint_save_freq: !!float 5e4
        checkpoint_save_replay_buffer: True
        checkpoint_save_vecnormalize: True
    use_progress_bar_callback: True
